Fix compile error
Fix compile error introduced by http://review.cyanogenmod.com/5197

frameworks/base/voip/java/android/net/sip/SipProfile.java:262: error 4: @param tag with name that doesn't match the parameter list: 'keep-alive'

Change-Id: I05f9c548ab9491fb6ddf6a6e367a5fcb2345b682